[tool.poetry]
name = "cw5-bd"
version = "0.1.0"
description = ""
authors = ["Helen85236"]
readme = "README.md"
packages = [{include = "cw5"}]

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
